<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FsYacc Include="Parser.fsy">
      <OtherFlags>--module Parser -v</OtherFlags>
    </FsYacc>
    <FsLex Include="Lexer.fsl">
      <OtherFlags>--module Lexer --unicode</OtherFlags>
    </FsLex>
    <Compile Include="Symbol.fs" />
    <Compile Include="Absyn.fs" />
    <Compile Include="$(FsYaccOutputFolder)Parser.fsi" />
    <Compile Include="$(FsYaccOutputFolder)Parser.fs" />
    <Compile Include="$(FsLexOutputFolder)Lexer.fs" />
    <Compile Include="Types.fs" />
    <Compile Include="Env.fs" />
    <Compile Include="Semant.fs" />
    <Compile Include="TigerCompiler.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsLexYacc" />
  </ItemGroup>
</Project>
