<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Config.fs" />
    <Compile Include="Chap02_Lexer.fs" />
    <Compile Include="Chap04_Parser.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Expecto" />
    <PackageReference Include="Unquote" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TigerCompiler/TigerCompiler.fsproj" />
  </ItemGroup>
</Project>
