name: Build and test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        global-json-file: global.json
    - name: Check formatting
      run: |
        dotnet tool restore
        dotnet fantomas --check src tests
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet run -c Release --no-build --project tests/TigerCompiler.Tests
